### ISSUE TITLE
Chopping Prompt

### ISSUE THREAD

**Issue by AvocadoOutlaw** [VORPCORE/vorp_lumberjack#11]
I can not get the prompt to cut down trees. I get no errors and have even pulled a fresh file. I have also made sure I am updated on everything. I have ran around in towns and out in areas I know that trees that are harvest able are. I have checked identifiers as well and can not get a prompt. Items are usable in the database as well.

**Comment by outsider31000** [comment]
have you updated vorp core ?

**Comment by lutzip0** [comment]
I have the same problem, Vorp Cor is updated with the latest version

**Comment by AvocadoOutlaw** [comment]
Yes Vorp core is updated!

**Comment by AvocadoOutlaw** [comment]
Following up on this

**Comment by outsider31000** [comment]
I have tested this and fixed it should be working now let me know. @AvocadoOutlaw
